version: "3"

services:
  broker:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1883:1883
      - 9002:9001
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: slin
      POSTGRES_DB: test
    ports:
      - 5431:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080